project:
  type: website
  output-dir: docs
  preview:
    port: 5540
    browser: false

website:
  title: "Michael Knitz"
  search:
    location: sidebar
    type: overlay
    limit: 50
  reader-mode: false
  sidebar:
    title: Michael Knitz
    style: "floating"
    collapse-level: 4
    contents:
      - section: "R"
        contents:
          - "Posts/2023-11-28_barplots/barplots.qmd"
          - "Posts/2023-11-28_r_function_gene_to_name/gene_to_name.qmd"
          - "Posts/2023-11-28_quarto_snippets/quarto_snippets.qmd"
          - "Posts/2023-11-28_R_data_structures/R_data_structures.qmd"
          - "Posts/2023-11-29_functions_in_environment/functions_in_environment.qmd"
      - section: "Misc"
        contents:
          - "Posts/2023-12-03_git_notes/git_notes.qmd"
          - "Posts/2023-11-30_repos_with_large_files/repos_with_large_files.qmd"

format:
  html:
    css: assets/custom.scss
    # bibliography: references.bib
    # csl: assets/nature-medicine.csl
    code-overflow: scroll
    code-tools: true
    # embed-resources: true
    highlight-style: github
    theme:
      light: lumen
    toc: true
    toc-expand: true
    toc-depth: 4
    toc-location: right
    toc-collapsed: false
    grid:
      sidebar-width: 300px
      body-width: 1000px
      margin-width: 500px
      gutter-width: 1.5rem
